# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Houssein Djirdeh
email: h.djirdeh@mail.utoronto.ca
description: > # this means to ignore newlines until "baseurl:"
  JavaScript and all things web
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://houssein.me" # the base hostname & protocol for your site
linkedin_username: Houssein Djirdeh
github_username:  housseindjirdeh
twitter_username: hdjirdeh
google_analytics: UA-66348622-2
plugins:
  - jekyll-sitemap
  - jekyll-feed

# Build settings
markdown: kramdown

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
  - package.json
  - workbox.config.js
  - node_modules